/* automatically generated by rust-bindgen 0.69.5 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub type __u64 = ::core::ffi::c_ulonglong;
pub type u64_ = __u64;
pub type __u32 = ::core::ffi::c_uint;
pub type u32_ = __u32;
pub type __u16 = ::core::ffi::c_ushort;
pub type u16_ = __u16;
pub type __be16 = __u16;
pub type __be32 = __u32;
pub type __s64 = ::core::ffi::c_longlong;
pub type __kernel_pid_t = ::core::ffi::c_int;
pub type __kernel_uid32_t = ::core::ffi::c_uint;
pub type __kernel_gid32_t = ::core::ffi::c_uint;
pub type __kernel_loff_t = ::core::ffi::c_longlong;
pub type __kernel_sa_family_t = ::core::ffi::c_ushort;
pub type uid_t = __kernel_uid32_t;
pub type gid_t = __kernel_gid32_t;
pub type pid_t = __kernel_pid_t;
extern "C" {
    pub fn shim_cgroup_subsys_id_memory_cgrp_id() -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_cgroup_subsys_id_memory_cgrp_id_exists() -> bool;
}
extern "C" {
    pub fn shim_cgroup_subsys_id_perf_event_cgrp_id() -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_cgroup_subsys_id_perf_event_cgrp_id_exists() -> bool;
}
extern "C" {
    pub fn shim_cgroup_subsys_id_cpu_cgrp_id() -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_cgroup_subsys_id_cpu_cgrp_id_exists() -> bool;
}
extern "C" {
    pub fn shim_cgroup_subsys_id_pids_cgrp_id() -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_cgroup_subsys_id_pids_cgrp_id_exists() -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kgid_t {
    pub val: gid_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kuid_t {
    pub val: uid_t,
}
extern "C" {
    pub fn shim_kuid_t_val(kuid_t: *mut kuid_t) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_kuid_t_val_user(kuid_t: *mut kuid_t) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_kuid_t_val_exists(kuid_t: *mut kuid_t) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kernel_cap_t {
    pub val: u64_,
}
extern "C" {
    pub fn shim_kernel_cap_t_val(kernel_cap_t: *mut kernel_cap_t) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_kernel_cap_t_val_user(kernel_cap_t: *mut kernel_cap_t) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_kernel_cap_t_val_exists(kernel_cap_t: *mut kernel_cap_t) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kernel_cap_t_older_v515 {
    pub cap: [u32_; 2usize],
}
extern "C" {
    pub fn shim_kernel_cap_t_older_v515_cap(
        kernel_cap_t_older_v515: *mut kernel_cap_t_older_v515,
    ) -> *mut ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_kernel_cap_t_older_v515_cap_user(
        kernel_cap_t_older_v515: *mut kernel_cap_t_older_v515,
    ) -> *mut ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_kernel_cap_t_older_v515_cap_exists(
        kernel_cap_t_older_v515: *mut kernel_cap_t_older_v515,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cred_cap_t_older_v515 {
    pub cap_effective: kernel_cap_t_older_v515,
}
extern "C" {
    pub fn shim_cred_cap_t_older_v515_cap_effective(
        cred_cap_t_older_v515: *mut cred_cap_t_older_v515,
    ) -> *mut kernel_cap_t_older_v515;
}
extern "C" {
    pub fn shim_cred_cap_t_older_v515_cap_effective_user(
        cred_cap_t_older_v515: *mut cred_cap_t_older_v515,
    ) -> *mut kernel_cap_t_older_v515;
}
extern "C" {
    pub fn shim_cred_cap_t_older_v515_cap_effective_exists(
        cred_cap_t_older_v515: *mut cred_cap_t_older_v515,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cred {
    pub uid: kuid_t,
    pub gid: kgid_t,
    pub cap_effective: kernel_cap_t,
}
extern "C" {
    pub fn shim_cred_uid(pcred: *mut cred) -> uid_t;
}
extern "C" {
    pub fn shim_cred_gid(pcred: *mut cred) -> gid_t;
}
extern "C" {
    pub fn shim_cred_cap_effective(pcred: *mut cred) -> u64_;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct qstr {
    pub hash_len: __u64,
    pub name: *const ::core::ffi::c_uchar,
}
extern "C" {
    pub fn shim_qstr_name(qstr: *mut qstr) -> *const ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_qstr_name_user(qstr: *mut qstr) -> *const ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_qstr_name_exists(qstr: *mut qstr) -> bool;
}
extern "C" {
    pub fn shim_qstr_hash_len(qstr: *mut qstr) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_qstr_hash_len_user(qstr: *mut qstr) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_qstr_hash_len_exists(qstr: *mut qstr) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vfsmount {
    pub mnt_root: *mut dentry,
}
extern "C" {
    pub fn shim_vfsmount_mnt_root(vfsmount: *mut vfsmount) -> *mut dentry;
}
extern "C" {
    pub fn shim_vfsmount_mnt_root_user(vfsmount: *mut vfsmount) -> *mut dentry;
}
extern "C" {
    pub fn shim_vfsmount_mnt_root_exists(vfsmount: *mut vfsmount) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mount {
    pub mnt_parent: *mut mount,
    pub mnt_mountpoint: *mut dentry,
    pub mnt: vfsmount,
    pub mnt_mp: *mut mountpoint,
}
extern "C" {
    pub fn shim_mount_mnt_parent(mount: *mut mount) -> *mut mount;
}
extern "C" {
    pub fn shim_mount_mnt_parent_user(mount: *mut mount) -> *mut mount;
}
extern "C" {
    pub fn shim_mount_mnt_parent_exists(mount: *mut mount) -> bool;
}
extern "C" {
    pub fn shim_mount_mnt_mountpoint(mount: *mut mount) -> *mut dentry;
}
extern "C" {
    pub fn shim_mount_mnt_mountpoint_user(mount: *mut mount) -> *mut dentry;
}
extern "C" {
    pub fn shim_mount_mnt_mountpoint_exists(mount: *mut mount) -> bool;
}
extern "C" {
    pub fn shim_mount_mnt(mount: *mut mount) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_mount_mnt_user(mount: *mut mount) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_mount_mnt_exists(mount: *mut mount) -> bool;
}
extern "C" {
    pub fn shim_mount_mnt_mp(mount: *mut mount) -> *mut mountpoint;
}
extern "C" {
    pub fn shim_mount_mnt_mp_user(mount: *mut mount) -> *mut mountpoint;
}
extern "C" {
    pub fn shim_mount_mnt_mp_exists(mount: *mut mount) -> bool;
}
extern "C" {
    pub fn shim_mount_from_vfsmount(vfs: *mut vfsmount) -> *mut mount;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct file_system_type {
    pub name: *const ::core::ffi::c_char,
}
extern "C" {
    pub fn shim_file_system_type_name(
        file_system_type: *mut file_system_type,
    ) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_file_system_type_name_user(
        file_system_type: *mut file_system_type,
    ) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_file_system_type_name_exists(file_system_type: *mut file_system_type) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct super_block {
    pub s_root: *mut dentry,
    pub s_type: *mut file_system_type,
}
extern "C" {
    pub fn shim_super_block_s_root(super_block: *mut super_block) -> *mut dentry;
}
extern "C" {
    pub fn shim_super_block_s_root_user(super_block: *mut super_block) -> *mut dentry;
}
extern "C" {
    pub fn shim_super_block_s_root_exists(super_block: *mut super_block) -> bool;
}
extern "C" {
    pub fn shim_super_block_s_type(super_block: *mut super_block) -> *mut file_system_type;
}
extern "C" {
    pub fn shim_super_block_s_type_user(super_block: *mut super_block) -> *mut file_system_type;
}
extern "C" {
    pub fn shim_super_block_s_type_exists(super_block: *mut super_block) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dentry {
    pub d_flags: ::core::ffi::c_uint,
    pub d_parent: *mut dentry,
    pub d_name: qstr,
    pub d_sb: *mut super_block,
    pub d_inode: *mut inode,
}
extern "C" {
    pub fn shim_dentry_d_parent(dentry: *mut dentry) -> *mut dentry;
}
extern "C" {
    pub fn shim_dentry_d_parent_user(dentry: *mut dentry) -> *mut dentry;
}
extern "C" {
    pub fn shim_dentry_d_parent_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_flags(dentry: *mut dentry) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_dentry_d_flags_user(dentry: *mut dentry) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_dentry_d_flags_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_name(dentry: *mut dentry) -> *mut qstr;
}
extern "C" {
    pub fn shim_dentry_d_name_user(dentry: *mut dentry) -> *mut qstr;
}
extern "C" {
    pub fn shim_dentry_d_name_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_sb(dentry: *mut dentry) -> *mut super_block;
}
extern "C" {
    pub fn shim_dentry_d_sb_user(dentry: *mut dentry) -> *mut super_block;
}
extern "C" {
    pub fn shim_dentry_d_sb_exists(dentry: *mut dentry) -> bool;
}
extern "C" {
    pub fn shim_dentry_d_inode(dentry: *mut dentry) -> *mut inode;
}
extern "C" {
    pub fn shim_dentry_d_inode_user(dentry: *mut dentry) -> *mut inode;
}
extern "C" {
    pub fn shim_dentry_d_inode_exists(dentry: *mut dentry) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mountpoint {
    pub m_dentry: *mut dentry,
}
extern "C" {
    pub fn shim_mountpoint_m_dentry(mountpoint: *mut mountpoint) -> *mut dentry;
}
extern "C" {
    pub fn shim_mountpoint_m_dentry_user(mountpoint: *mut mountpoint) -> *mut dentry;
}
extern "C" {
    pub fn shim_mountpoint_m_dentry_exists(mountpoint: *mut mountpoint) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct path {
    pub mnt: *mut vfsmount,
    pub dentry: *mut dentry,
}
extern "C" {
    pub fn shim_path_mnt(path: *mut path) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_path_mnt_user(path: *mut path) -> *mut vfsmount;
}
extern "C" {
    pub fn shim_path_mnt_exists(path: *mut path) -> bool;
}
extern "C" {
    pub fn shim_path_dentry(path: *mut path) -> *mut dentry;
}
extern "C" {
    pub fn shim_path_dentry_user(path: *mut path) -> *mut dentry;
}
extern "C" {
    pub fn shim_path_dentry_exists(path: *mut path) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fs_struct {
    pub root: path,
    pub pwd: path,
}
extern "C" {
    pub fn shim_fs_struct_root(fs_struct: *mut fs_struct) -> *mut path;
}
extern "C" {
    pub fn shim_fs_struct_root_user(fs_struct: *mut fs_struct) -> *mut path;
}
extern "C" {
    pub fn shim_fs_struct_root_exists(fs_struct: *mut fs_struct) -> bool;
}
extern "C" {
    pub fn shim_fs_struct_pwd(fs_struct: *mut fs_struct) -> *mut path;
}
extern "C" {
    pub fn shim_fs_struct_pwd_user(fs_struct: *mut fs_struct) -> *mut path;
}
extern "C" {
    pub fn shim_fs_struct_pwd_exists(fs_struct: *mut fs_struct) -> bool;
}
pub type time64_t = __s64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec64 {
    pub tv_sec: time64_t,
    pub tv_nsec: ::core::ffi::c_long,
}
pub type umode_t = ::core::ffi::c_ushort;
pub type loff_t = __kernel_loff_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct inode {
    pub i_mode: umode_t,
    pub i_ino: ::core::ffi::c_ulong,
    pub i_sb: *mut super_block,
    pub i_size: loff_t,
    pub i_atime_sec: time64_t,
    pub i_mtime_sec: time64_t,
    pub i_ctime_sec: time64_t,
    pub i_atime_nsec: u32_,
    pub i_mtime_nsec: u32_,
    pub i_ctime_nsec: u32_,
    pub __bindgen_anon_1: inode__bindgen_ty_1,
    pub __bindgen_anon_2: inode__bindgen_ty_2,
    pub __bindgen_anon_3: inode__bindgen_ty_3,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union inode__bindgen_ty_1 {
    pub i_atime: timespec64,
    pub __i_atime: timespec64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union inode__bindgen_ty_2 {
    pub i_mtime: timespec64,
    pub __i_mtime: timespec64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union inode__bindgen_ty_3 {
    pub i_ctime: timespec64,
    pub __i_ctime: timespec64,
}
extern "C" {
    pub fn shim_inode_i_ino(inode: *mut inode) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_inode_i_ino_user(inode: *mut inode) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_inode_i_ino_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_mode(inode: *mut inode) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_inode_i_mode_user(inode: *mut inode) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_inode_i_mode_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_sb(inode: *mut inode) -> *mut super_block;
}
extern "C" {
    pub fn shim_inode_i_sb_user(inode: *mut inode) -> *mut super_block;
}
extern "C" {
    pub fn shim_inode_i_sb_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_size(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_size_user(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_size_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_atime(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode_i_atime_user(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode_i_atime_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode___i_atime(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode___i_atime_user(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode___i_atime_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_atime_sec(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_atime_sec_user(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_atime_sec_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_atime_nsec(inode: *mut inode) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_inode_i_atime_nsec_user(inode: *mut inode) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_inode_i_atime_nsec_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_mtime(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode_i_mtime_user(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode_i_mtime_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode___i_mtime(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode___i_mtime_user(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode___i_mtime_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_mtime_sec(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_mtime_sec_user(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_mtime_sec_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_mtime_nsec(inode: *mut inode) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_inode_i_mtime_nsec_user(inode: *mut inode) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_inode_i_mtime_nsec_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_ctime(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode_i_ctime_user(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode_i_ctime_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode___i_ctime(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode___i_ctime_user(inode: *mut inode) -> timespec64;
}
extern "C" {
    pub fn shim_inode___i_ctime_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_ctime_sec(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_ctime_sec_user(inode: *mut inode) -> ::core::ffi::c_longlong;
}
extern "C" {
    pub fn shim_inode_i_ctime_sec_exists(inode: *mut inode) -> bool;
}
extern "C" {
    pub fn shim_inode_i_ctime_nsec(inode: *mut inode) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_inode_i_ctime_nsec_user(inode: *mut inode) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_inode_i_ctime_nsec_exists(inode: *mut inode) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct file {
    pub f_inode: *mut inode,
    pub f_path: path,
    pub f_flags: ::core::ffi::c_uint,
    pub private_data: *mut ::core::ffi::c_void,
}
extern "C" {
    pub fn shim_file_f_path(file: *mut file) -> *mut path;
}
extern "C" {
    pub fn shim_file_f_path_user(file: *mut file) -> *mut path;
}
extern "C" {
    pub fn shim_file_f_path_exists(file: *mut file) -> bool;
}
extern "C" {
    pub fn shim_file_f_inode(file: *mut file) -> *mut inode;
}
extern "C" {
    pub fn shim_file_f_inode_user(file: *mut file) -> *mut inode;
}
extern "C" {
    pub fn shim_file_f_inode_exists(file: *mut file) -> bool;
}
extern "C" {
    pub fn shim_file_private_data(file: *mut file) -> *mut ::core::ffi::c_void;
}
extern "C" {
    pub fn shim_file_private_data_user(file: *mut file) -> *mut ::core::ffi::c_void;
}
extern "C" {
    pub fn shim_file_private_data_exists(file: *mut file) -> bool;
}
extern "C" {
    pub fn shim_file_f_flags(file: *mut file) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_file_f_flags_user(file: *mut file) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_file_f_flags_exists(file: *mut file) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fd {
    pub file: *mut file,
    pub flags: ::core::ffi::c_uint,
}
extern "C" {
    pub fn shim_fd_file(fd: *mut fd) -> *mut file;
}
extern "C" {
    pub fn shim_fd_file_user(fd: *mut fd) -> *mut file;
}
extern "C" {
    pub fn shim_fd_file_exists(fd: *mut fd) -> bool;
}
extern "C" {
    pub fn shim_fd_flags(fd: *mut fd) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_fd_flags_user(fd: *mut fd) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_fd_flags_exists(fd: *mut fd) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct filename {
    pub name: *const ::core::ffi::c_char,
    pub uptr: *const ::core::ffi::c_char,
}
extern "C" {
    pub fn shim_filename_name(filename: *mut filename) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_filename_name_user(filename: *mut filename) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_filename_name_exists(filename: *mut filename) -> bool;
}
extern "C" {
    pub fn shim_filename_uptr(filename: *mut filename) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_filename_uptr_user(filename: *mut filename) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_filename_uptr_exists(filename: *mut filename) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mm_struct {
    pub arg_start: ::core::ffi::c_ulong,
    pub arg_end: ::core::ffi::c_ulong,
    pub exe_file: *mut file,
}
extern "C" {
    pub fn shim_mm_struct_arg_start(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_start_user(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_start_exists(mm_struct: *mut mm_struct) -> bool;
}
extern "C" {
    pub fn shim_mm_struct_arg_end(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_end_user(mm_struct: *mut mm_struct) -> ::core::ffi::c_ulong;
}
extern "C" {
    pub fn shim_mm_struct_arg_end_exists(mm_struct: *mut mm_struct) -> bool;
}
extern "C" {
    pub fn shim_mm_struct_exe_file(mm_struct: *mut mm_struct) -> *mut file;
}
extern "C" {
    pub fn shim_mm_struct_exe_file_user(mm_struct: *mut mm_struct) -> *mut file;
}
extern "C" {
    pub fn shim_mm_struct_exe_file_exists(mm_struct: *mut mm_struct) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ns_common {
    pub inum: ::core::ffi::c_uint,
}
extern "C" {
    pub fn shim_ns_common_inum(ns_common: *mut ns_common) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_ns_common_inum_user(ns_common: *mut ns_common) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_ns_common_inum_exists(ns_common: *mut ns_common) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mnt_namespace {
    pub ns: ns_common,
    pub root: *mut mount,
    pub mounts: ::core::ffi::c_uint,
}
extern "C" {
    pub fn shim_mnt_namespace_ns(mnt_namespace: *mut mnt_namespace) -> *mut ns_common;
}
extern "C" {
    pub fn shim_mnt_namespace_ns_user(mnt_namespace: *mut mnt_namespace) -> *mut ns_common;
}
extern "C" {
    pub fn shim_mnt_namespace_ns_exists(mnt_namespace: *mut mnt_namespace) -> bool;
}
extern "C" {
    pub fn shim_mnt_namespace_root(mnt_namespace: *mut mnt_namespace) -> *mut mount;
}
extern "C" {
    pub fn shim_mnt_namespace_root_user(mnt_namespace: *mut mnt_namespace) -> *mut mount;
}
extern "C" {
    pub fn shim_mnt_namespace_root_exists(mnt_namespace: *mut mnt_namespace) -> bool;
}
extern "C" {
    pub fn shim_mnt_namespace_mounts(mnt_namespace: *mut mnt_namespace) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_mnt_namespace_mounts_user(mnt_namespace: *mut mnt_namespace)
        -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_mnt_namespace_mounts_exists(mnt_namespace: *mut mnt_namespace) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct new_utsname {
    pub sysname: [::core::ffi::c_char; 65usize],
    pub nodename: [::core::ffi::c_char; 65usize],
    pub release: [::core::ffi::c_char; 65usize],
    pub version: [::core::ffi::c_char; 65usize],
    pub machine: [::core::ffi::c_char; 65usize],
    pub domainname: [::core::ffi::c_char; 65usize],
}
extern "C" {
    pub fn shim_new_utsname_sysname(new_utsname: *mut new_utsname) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_sysname_user(new_utsname: *mut new_utsname)
        -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_sysname_exists(new_utsname: *mut new_utsname) -> bool;
}
extern "C" {
    pub fn shim_new_utsname_nodename(new_utsname: *mut new_utsname) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_nodename_user(
        new_utsname: *mut new_utsname,
    ) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_nodename_exists(new_utsname: *mut new_utsname) -> bool;
}
extern "C" {
    pub fn shim_new_utsname_release(new_utsname: *mut new_utsname) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_release_user(new_utsname: *mut new_utsname)
        -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_release_exists(new_utsname: *mut new_utsname) -> bool;
}
extern "C" {
    pub fn shim_new_utsname_version(new_utsname: *mut new_utsname) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_version_user(new_utsname: *mut new_utsname)
        -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_version_exists(new_utsname: *mut new_utsname) -> bool;
}
extern "C" {
    pub fn shim_new_utsname_machine(new_utsname: *mut new_utsname) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_machine_user(new_utsname: *mut new_utsname)
        -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_machine_exists(new_utsname: *mut new_utsname) -> bool;
}
extern "C" {
    pub fn shim_new_utsname_domainname(new_utsname: *mut new_utsname) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_domainname_user(
        new_utsname: *mut new_utsname,
    ) -> *mut ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_new_utsname_domainname_exists(new_utsname: *mut new_utsname) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uts_namespace {
    pub name: new_utsname,
    pub ns: ns_common,
}
extern "C" {
    pub fn shim_uts_namespace_ns(uts_namespace: *mut uts_namespace) -> *mut ns_common;
}
extern "C" {
    pub fn shim_uts_namespace_ns_user(uts_namespace: *mut uts_namespace) -> *mut ns_common;
}
extern "C" {
    pub fn shim_uts_namespace_ns_exists(uts_namespace: *mut uts_namespace) -> bool;
}
extern "C" {
    pub fn shim_uts_namespace_name(uts_namespace: *mut uts_namespace) -> *mut new_utsname;
}
extern "C" {
    pub fn shim_uts_namespace_name_user(uts_namespace: *mut uts_namespace) -> *mut new_utsname;
}
extern "C" {
    pub fn shim_uts_namespace_name_exists(uts_namespace: *mut uts_namespace) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct upid {
    pub nr: ::core::ffi::c_int,
    pub ns: *mut pid_namespace,
}
extern "C" {
    pub fn shim_upid_nr(upid: *mut upid) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_upid_nr_user(upid: *mut upid) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_upid_nr_exists(upid: *mut upid) -> bool;
}
#[repr(C)]
#[derive(Debug)]
pub struct pid {
    pub level: ::core::ffi::c_uint,
    pub numbers: __IncompleteArrayField<upid>,
}
extern "C" {
    pub fn shim_pid_level(pid: *mut pid) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_pid_level_user(pid: *mut pid) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_pid_level_exists(pid: *mut pid) -> bool;
}
extern "C" {
    pub fn shim_pid_nr_at_level(pid: *mut pid, level: ::core::ffi::c_uint) -> ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pid_namespace {
    pub level: ::core::ffi::c_uint,
}
extern "C" {
    pub fn shim_pid_namespace_level(pid_namespace: *mut pid_namespace) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_pid_namespace_level_user(pid_namespace: *mut pid_namespace) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_pid_namespace_level_exists(pid_namespace: *mut pid_namespace) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nsproxy {
    pub mnt_ns: *mut mnt_namespace,
    pub uts_ns: *mut uts_namespace,
    pub pid_ns_for_children: *mut pid_namespace,
}
extern "C" {
    pub fn shim_nsproxy_mnt_ns(nsproxy: *mut nsproxy) -> *mut mnt_namespace;
}
extern "C" {
    pub fn shim_nsproxy_mnt_ns_user(nsproxy: *mut nsproxy) -> *mut mnt_namespace;
}
extern "C" {
    pub fn shim_nsproxy_mnt_ns_exists(nsproxy: *mut nsproxy) -> bool;
}
extern "C" {
    pub fn shim_nsproxy_uts_ns(nsproxy: *mut nsproxy) -> *mut uts_namespace;
}
extern "C" {
    pub fn shim_nsproxy_uts_ns_user(nsproxy: *mut nsproxy) -> *mut uts_namespace;
}
extern "C" {
    pub fn shim_nsproxy_uts_ns_exists(nsproxy: *mut nsproxy) -> bool;
}
extern "C" {
    pub fn shim_nsproxy_pid_ns_for_children(nsproxy: *mut nsproxy) -> *mut pid_namespace;
}
extern "C" {
    pub fn shim_nsproxy_pid_ns_for_children_user(nsproxy: *mut nsproxy) -> *mut pid_namespace;
}
extern "C" {
    pub fn shim_nsproxy_pid_ns_for_children_exists(nsproxy: *mut nsproxy) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kernfs_node___older_v55 {
    pub name: *const ::core::ffi::c_char,
    pub id: kernfs_node___older_v55__bindgen_ty_1,
    pub parent: *mut kernfs_node___older_v55,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kernfs_node___older_v55__bindgen_ty_1 {
    pub __bindgen_anon_1: kernfs_node___older_v55__bindgen_ty_1__bindgen_ty_1,
    pub id: u64_,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kernfs_node___older_v55__bindgen_ty_1__bindgen_ty_1 {
    pub ino: u32_,
    pub generation: u32_,
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_id(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> kernfs_node___older_v55__bindgen_ty_1;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_id_user(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> kernfs_node___older_v55__bindgen_ty_1;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_id_exists(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> bool;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_parent(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> *mut kernfs_node___older_v55;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_parent_user(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> *mut kernfs_node___older_v55;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_parent_exists(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> bool;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_name(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_name_user(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_kernfs_node___older_v55_name_exists(
        kernfs_node___older_v55: *mut kernfs_node___older_v55,
    ) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rh_kabi_hidden_172 {
    pub id: rh_kabi_hidden_172__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union rh_kabi_hidden_172__bindgen_ty_1 {
    pub __bindgen_anon_1: rh_kabi_hidden_172__bindgen_ty_1__bindgen_ty_1,
    pub id: u64_,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rh_kabi_hidden_172__bindgen_ty_1__bindgen_ty_1 {
    pub ino: u32_,
    pub generation: u32_,
}
extern "C" {
    pub fn shim_rh_kabi_hidden_172_id(
        rh_kabi_hidden_172: *mut rh_kabi_hidden_172,
    ) -> rh_kabi_hidden_172__bindgen_ty_1;
}
extern "C" {
    pub fn shim_rh_kabi_hidden_172_id_user(
        rh_kabi_hidden_172: *mut rh_kabi_hidden_172,
    ) -> rh_kabi_hidden_172__bindgen_ty_1;
}
extern "C" {
    pub fn shim_rh_kabi_hidden_172_id_exists(rh_kabi_hidden_172: *mut rh_kabi_hidden_172) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kernfs_node___rh8 {
    pub name: *const ::core::ffi::c_char,
    pub __bindgen_anon_1: kernfs_node___rh8__bindgen_ty_1,
    pub parent: *mut kernfs_node___rh8,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kernfs_node___rh8__bindgen_ty_1 {
    pub id: u64_,
    pub rh_id: rh_kabi_hidden_172,
    pub __bindgen_anon_1: kernfs_node___rh8__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[repr(align(1))]
#[derive(Copy, Clone)]
pub struct kernfs_node___rh8__bindgen_ty_1__bindgen_ty_1 {
    pub bindgen_union_field: [u8; 0usize],
}
extern "C" {
    pub fn shim_kernfs_node___rh8_id(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_id_user(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_id_exists(kernfs_node___rh8: *mut kernfs_node___rh8) -> bool;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_rh_id(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> rh_kabi_hidden_172;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_rh_id_user(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> rh_kabi_hidden_172;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_rh_id_exists(kernfs_node___rh8: *mut kernfs_node___rh8) -> bool;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_name(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_name_user(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_name_exists(kernfs_node___rh8: *mut kernfs_node___rh8) -> bool;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_parent(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> *mut kernfs_node___rh8;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_parent_user(
        kernfs_node___rh8: *mut kernfs_node___rh8,
    ) -> *mut kernfs_node___rh8;
}
extern "C" {
    pub fn shim_kernfs_node___rh8_parent_exists(kernfs_node___rh8: *mut kernfs_node___rh8) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kernfs_node {
    pub parent: *mut kernfs_node,
    pub name: *const ::core::ffi::c_char,
    pub id: u64_,
}
extern "C" {
    pub fn shim_kernfs_node_parent(kernfs_node: *mut kernfs_node) -> *mut kernfs_node;
}
extern "C" {
    pub fn shim_kernfs_node_parent_user(kernfs_node: *mut kernfs_node) -> *mut kernfs_node;
}
extern "C" {
    pub fn shim_kernfs_node_parent_exists(kernfs_node: *mut kernfs_node) -> bool;
}
extern "C" {
    pub fn shim_kernfs_node_name(kernfs_node: *mut kernfs_node) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_kernfs_node_name_user(kernfs_node: *mut kernfs_node) -> *const ::core::ffi::c_char;
}
extern "C" {
    pub fn shim_kernfs_node_name_exists(kernfs_node: *mut kernfs_node) -> bool;
}
extern "C" {
    pub fn shim_kernfs_node_id(kernfs_node: *mut kernfs_node) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_kernfs_node_id_user(kernfs_node: *mut kernfs_node) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_kernfs_node_id_exists(kernfs_node: *mut kernfs_node) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cgroup {
    pub kn: *mut kernfs_node,
}
extern "C" {
    pub fn shim_cgroup_kn(cgroup: *mut cgroup) -> *mut kernfs_node;
}
extern "C" {
    pub fn shim_cgroup_kn_user(cgroup: *mut cgroup) -> *mut kernfs_node;
}
extern "C" {
    pub fn shim_cgroup_kn_exists(cgroup: *mut cgroup) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cgroup_subsys_state {
    pub cgroup: *mut cgroup,
}
extern "C" {
    pub fn shim_cgroup_subsys_state_cgroup(
        cgroup_subsys_state: *mut cgroup_subsys_state,
    ) -> *mut cgroup;
}
extern "C" {
    pub fn shim_cgroup_subsys_state_cgroup_user(
        cgroup_subsys_state: *mut cgroup_subsys_state,
    ) -> *mut cgroup;
}
extern "C" {
    pub fn shim_cgroup_subsys_state_cgroup_exists(
        cgroup_subsys_state: *mut cgroup_subsys_state,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct task_group {
    pub css: cgroup_subsys_state,
}
extern "C" {
    pub fn shim_task_group_css(task_group: *mut task_group) -> *mut cgroup_subsys_state;
}
extern "C" {
    pub fn shim_task_group_css_user(task_group: *mut task_group) -> *mut cgroup_subsys_state;
}
extern "C" {
    pub fn shim_task_group_css_exists(task_group: *mut task_group) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fdtable {
    pub max_fds: ::core::ffi::c_uint,
    pub fd: *mut *mut file,
}
extern "C" {
    pub fn shim_fdtable_max_fds(fdtable: *mut fdtable) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_fdtable_max_fds_user(fdtable: *mut fdtable) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_fdtable_max_fds_exists(fdtable: *mut fdtable) -> bool;
}
extern "C" {
    pub fn shim_fdtable_fd(fdtable: *mut fdtable) -> *mut *mut file;
}
extern "C" {
    pub fn shim_fdtable_fd_user(fdtable: *mut fdtable) -> *mut *mut file;
}
extern "C" {
    pub fn shim_fdtable_fd_exists(fdtable: *mut fdtable) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct files_struct {
    pub fdt: *mut fdtable,
    pub fd_array: [*mut file; 1usize],
}
extern "C" {
    pub fn shim_files_struct_fd_array(files_struct: *mut files_struct) -> *mut *mut file;
}
extern "C" {
    pub fn shim_files_struct_fd_array_user(files_struct: *mut files_struct) -> *mut *mut file;
}
extern "C" {
    pub fn shim_files_struct_fd_array_exists(files_struct: *mut files_struct) -> bool;
}
extern "C" {
    pub fn shim_files_struct_fdt(files_struct: *mut files_struct) -> *mut fdtable;
}
extern "C" {
    pub fn shim_files_struct_fdt_user(files_struct: *mut files_struct) -> *mut fdtable;
}
extern "C" {
    pub fn shim_files_struct_fdt_exists(files_struct: *mut files_struct) -> bool;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct task_struct {
    pub flags: ::core::ffi::c_uint,
    pub pid: pid_t,
    pub start_time: __u64,
    pub __bindgen_anon_1: task_struct__bindgen_ty_1,
    pub tgid: pid_t,
    pub comm: [::core::ffi::c_uchar; 16usize],
    pub cred: *mut cred,
    pub real_parent: *mut task_struct,
    pub group_leader: *mut task_struct,
    pub mm: *mut mm_struct,
    pub files: *mut files_struct,
    pub nsproxy: *mut nsproxy,
    pub sched_task_group: *mut task_group,
    pub fs: *mut fs_struct,
    pub thread_pid: *mut pid,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union task_struct__bindgen_ty_1 {
    pub start_boottime: __u64,
    pub real_start_time: __u64,
}
extern "C" {
    pub fn shim_task_struct_flags(task_struct: *mut task_struct) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_task_struct_flags_user(task_struct: *mut task_struct) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_task_struct_flags_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_start_time(task_struct: *mut task_struct) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_task_struct_start_time_user(
        task_struct: *mut task_struct,
    ) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_task_struct_start_time_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_start_boottime(
        task_struct: *mut task_struct,
    ) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_task_struct_start_boottime_user(
        task_struct: *mut task_struct,
    ) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_task_struct_start_boottime_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_real_start_time(
        task_struct: *mut task_struct,
    ) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_task_struct_real_start_time_user(
        task_struct: *mut task_struct,
    ) -> ::core::ffi::c_ulonglong;
}
extern "C" {
    pub fn shim_task_struct_real_start_time_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_comm(task_struct: *mut task_struct) -> *mut ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_task_struct_comm_user(task_struct: *mut task_struct) -> *mut ::core::ffi::c_uchar;
}
extern "C" {
    pub fn shim_task_struct_comm_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_pid(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_pid_user(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_pid_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_tgid(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_tgid_user(task_struct: *mut task_struct) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn shim_task_struct_tgid_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_cred(task_struct: *mut task_struct) -> *mut cred;
}
extern "C" {
    pub fn shim_task_struct_cred_user(task_struct: *mut task_struct) -> *mut cred;
}
extern "C" {
    pub fn shim_task_struct_cred_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_group_leader(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_group_leader_user(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_group_leader_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_real_parent(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_real_parent_user(task_struct: *mut task_struct) -> *mut task_struct;
}
extern "C" {
    pub fn shim_task_struct_real_parent_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_mm(task_struct: *mut task_struct) -> *mut mm_struct;
}
extern "C" {
    pub fn shim_task_struct_mm_user(task_struct: *mut task_struct) -> *mut mm_struct;
}
extern "C" {
    pub fn shim_task_struct_mm_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_files(task_struct: *mut task_struct) -> *mut files_struct;
}
extern "C" {
    pub fn shim_task_struct_files_user(task_struct: *mut task_struct) -> *mut files_struct;
}
extern "C" {
    pub fn shim_task_struct_files_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_nsproxy(task_struct: *mut task_struct) -> *mut nsproxy;
}
extern "C" {
    pub fn shim_task_struct_nsproxy_user(task_struct: *mut task_struct) -> *mut nsproxy;
}
extern "C" {
    pub fn shim_task_struct_nsproxy_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_sched_task_group(task_struct: *mut task_struct) -> *mut task_group;
}
extern "C" {
    pub fn shim_task_struct_sched_task_group_user(task_struct: *mut task_struct)
        -> *mut task_group;
}
extern "C" {
    pub fn shim_task_struct_sched_task_group_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_fs(task_struct: *mut task_struct) -> *mut fs_struct;
}
extern "C" {
    pub fn shim_task_struct_fs_user(task_struct: *mut task_struct) -> *mut fs_struct;
}
extern "C" {
    pub fn shim_task_struct_fs_exists(task_struct: *mut task_struct) -> bool;
}
extern "C" {
    pub fn shim_task_struct_thread_pid(task_struct: *mut task_struct) -> *mut pid;
}
extern "C" {
    pub fn shim_task_struct_thread_pid_user(task_struct: *mut task_struct) -> *mut pid;
}
extern "C" {
    pub fn shim_task_struct_thread_pid_exists(task_struct: *mut task_struct) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct linux_binprm {
    pub mm: *mut mm_struct,
    pub file: *mut file,
    pub cred: *mut cred,
}
extern "C" {
    pub fn shim_linux_binprm_mm(linux_binprm: *mut linux_binprm) -> *mut mm_struct;
}
extern "C" {
    pub fn shim_linux_binprm_mm_user(linux_binprm: *mut linux_binprm) -> *mut mm_struct;
}
extern "C" {
    pub fn shim_linux_binprm_mm_exists(linux_binprm: *mut linux_binprm) -> bool;
}
extern "C" {
    pub fn shim_linux_binprm_file(linux_binprm: *mut linux_binprm) -> *mut file;
}
extern "C" {
    pub fn shim_linux_binprm_file_user(linux_binprm: *mut linux_binprm) -> *mut file;
}
extern "C" {
    pub fn shim_linux_binprm_file_exists(linux_binprm: *mut linux_binprm) -> bool;
}
extern "C" {
    pub fn shim_linux_binprm_cred(linux_binprm: *mut linux_binprm) -> *mut cred;
}
extern "C" {
    pub fn shim_linux_binprm_cred_user(linux_binprm: *mut linux_binprm) -> *mut cred;
}
extern "C" {
    pub fn shim_linux_binprm_cred_exists(linux_binprm: *mut linux_binprm) -> bool;
}
pub type sa_family_t = __kernel_sa_family_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr {
    pub sa_family: sa_family_t,
}
extern "C" {
    pub fn shim_sockaddr_sa_family(sockaddr: *mut sockaddr) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_sa_family_user(sockaddr: *mut sockaddr) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_sa_family_exists(sockaddr: *mut sockaddr) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct in_addr {
    pub s_addr: __be32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_in {
    pub sin_family: __kernel_sa_family_t,
    pub sin_port: __be16,
    pub sin_addr: in_addr,
    pub __pad: [::core::ffi::c_uchar; 8usize],
}
extern "C" {
    pub fn shim_sockaddr_in_sin_family(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_family_user(sockaddr_in: *mut sockaddr_in)
        -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_family_exists(sockaddr_in: *mut sockaddr_in) -> bool;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_port(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_port_user(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sockaddr_in_sin_port_exists(sockaddr_in: *mut sockaddr_in) -> bool;
}
extern "C" {
    pub fn shim_sockaddr_in_s_addr(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_sockaddr_in_s_addr_user(sockaddr_in: *mut sockaddr_in) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_sockaddr_in_s_addr_exists(sockaddr_in: *mut sockaddr_in) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sock_common {
    pub skc_family: ::core::ffi::c_ushort,
    pub skc_daddr: __be32,
    pub skc_rcv_saddr: __be32,
    pub skc_dport: __be16,
    pub skc_num: __u16,
}
extern "C" {
    pub fn shim_sock_common_skc_family(sock_common: *mut sock_common) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_common_skc_family_user(sock_common: *mut sock_common)
        -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_common_skc_family_exists(sock_common: *mut sock_common) -> bool;
}
extern "C" {
    pub fn shim_sock_common_skc_daddr(sock_common: *mut sock_common) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_sock_common_skc_daddr_user(sock_common: *mut sock_common) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_sock_common_skc_daddr_exists(sock_common: *mut sock_common) -> bool;
}
extern "C" {
    pub fn shim_sock_common_skc_rcv_saddr(sock_common: *mut sock_common) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_sock_common_skc_rcv_saddr_user(
        sock_common: *mut sock_common,
    ) -> ::core::ffi::c_uint;
}
extern "C" {
    pub fn shim_sock_common_skc_rcv_saddr_exists(sock_common: *mut sock_common) -> bool;
}
extern "C" {
    pub fn shim_sock_common_skc_dport(sock_common: *mut sock_common) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_common_skc_dport_user(sock_common: *mut sock_common) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_common_skc_dport_exists(sock_common: *mut sock_common) -> bool;
}
extern "C" {
    pub fn shim_sock_common_skc_num(sock_common: *mut sock_common) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_common_skc_num_user(sock_common: *mut sock_common) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_common_skc_num_exists(sock_common: *mut sock_common) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sock {
    pub __sk_common: sock_common,
    pub sk_uid: kuid_t,
    pub sk_type: u16_,
}
extern "C" {
    pub fn shim_sock___sk_common(sock: *mut sock) -> *mut sock_common;
}
extern "C" {
    pub fn shim_sock___sk_common_user(sock: *mut sock) -> *mut sock_common;
}
extern "C" {
    pub fn shim_sock___sk_common_exists(sock: *mut sock) -> bool;
}
extern "C" {
    pub fn shim_sock_sk_uid(sock: *mut sock) -> kuid_t;
}
extern "C" {
    pub fn shim_sock_sk_uid_user(sock: *mut sock) -> kuid_t;
}
extern "C" {
    pub fn shim_sock_sk_uid_exists(sock: *mut sock) -> bool;
}
extern "C" {
    pub fn shim_sock_sk_type(sock: *mut sock) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_sk_type_user(sock: *mut sock) -> ::core::ffi::c_ushort;
}
extern "C" {
    pub fn shim_sock_sk_type_exists(sock: *mut sock) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct unix_sock {
    pub peer: *mut sock,
    pub path: path,
}
extern "C" {
    pub fn shim_unix_sock_peer(unix_sock: *mut unix_sock) -> *mut sock;
}
extern "C" {
    pub fn shim_unix_sock_peer_user(unix_sock: *mut unix_sock) -> *mut sock;
}
extern "C" {
    pub fn shim_unix_sock_peer_exists(unix_sock: *mut unix_sock) -> bool;
}
extern "C" {
    pub fn shim_unix_sock_path(unix_sock: *mut unix_sock) -> *mut path;
}
extern "C" {
    pub fn shim_unix_sock_path_user(unix_sock: *mut unix_sock) -> *mut path;
}
extern "C" {
    pub fn shim_unix_sock_path_exists(unix_sock: *mut unix_sock) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct socket {
    pub file: *mut file,
    pub sk: *mut sock,
}
extern "C" {
    pub fn shim_socket_file(socket: *mut socket) -> *mut file;
}
extern "C" {
    pub fn shim_socket_file_user(socket: *mut socket) -> *mut file;
}
extern "C" {
    pub fn shim_socket_file_exists(socket: *mut socket) -> bool;
}
extern "C" {
    pub fn shim_socket_sk(socket: *mut socket) -> *mut sock;
}
extern "C" {
    pub fn shim_socket_sk_user(socket: *mut socket) -> *mut sock;
}
extern "C" {
    pub fn shim_socket_sk_exists(socket: *mut socket) -> bool;
}
